name: Mobile CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'mobile/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'mobile/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      - name: Get dependencies
        working-directory: ./mobile
        run: flutter pub get

      - name: Analyze code
        working-directory: ./mobile
        run: flutter analyze || true

      - name: Format check
        working-directory: ./mobile
        run: flutter format --set-exit-if-changed . || true

